### ISSUE TITLE
"After updating all applications" command does not parse variables

### ISSUE THREAD

**Issue by martinl88** [canneverbe/Ketarin#11]
"After updating all applications" commands do not parse variables. 
With "After updating an application" variables work just fine

![2020-08-17_11-50-46_mRemoteNG](https://user-images.githubusercontent.com/328396/90377170-4669dc80-e080-11ea-9cc9-c3552adb4e27.png)

**Comment by shawnkhall** [comment]
Hi, @martinl88 , This is not a bug. Rather, I think the problem is actually with your script. You're using "{f}" and it's not in context since it's no longer processing a single application so there's no "file" to get information about. This is explained in the Wiki [here](https://wiki.ketarin.org/index.php/Special_variables). 
`preceded by "f:" (for example {f:dd}) to extract the values from the downloaded file date`
You should just be using `ketarin-{yyyy}-{MM}-{dd}.txt` not `ketarin-{f:yyyy}-{f:MM}-{f:dd}.txt`
